### ISSUE TITLE
Converting Torch Pretrained weights

### ISSUE THREAD

**Issue by Perseus14** [gzuidhof/nn-transfer#6]
I don't understand how to convert pretrained weights of a torch model. In the example you have defined a model and converted the weights, how do I do that with only the ".pth" torch weight file? Is there any command line execution like 

`convert torch_weights.pth keras_weights.npy`

Thank you

**Comment by gzuidhof** [comment]
You do it by defining the network, it is not possible to tell the architecture from just the weights.  otherwise there is no way (using nn-transfer). Also this is for pytorch models, not torch (although maybe that was what you meant.

You can try something like [MMdnn](https://github.com/Microsoft/MMdnn), but I doubt that will get as far with just the weights file.
